[package]
name = "smart-unit-converter"
version = "1.0.0"
edition = "2021"
authors = ["BakrLabs <your-email@example.com>"]
description = "A context-aware, highly intuitive command-line unit converter written in Rust that understands natural language."
readme = "README.md"
repository = "https://github.com/BakrLabs/unit-converter"
license = "Apache-2.0"
keywords = ["converter", "units", "cli", "currency", "rust"]
categories = ["command-line-utilities", "science"]

[[bin]]
name = "suc"
path = "src/main.rs"

[dependencies]
colored = "2.1.0"
clap = { version = "4.5", features = ["derive"] }
thiserror = "1.0"
evalexpr = "11"
rustyline = "14.0.0"
regex = "1.10.4"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }